// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMCHAaZjmXBQABr5NP3SGTmQPWEBMPVG4',
    appId: '1:2852225446:web:dcb8315cca2284bc074f67',
    messagingSenderId: '2852225446',
    projectId: 'study-timer-backend',
    authDomain: 'study-timer-backend.firebaseapp.com',
    storageBucket: 'study-timer-backend.firebasestorage.app',
    measurementId: 'G-DZXLKDTDQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpvpeHnkPr5U8vo8QWgrBfqNJCPxHdT_A',
    appId: '1:2852225446:android:680220f34ac21b86074f67',
    messagingSenderId: '2852225446',
    projectId: 'study-timer-backend',
    storageBucket: 'study-timer-backend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGCer_T_1S60YWAfbUhv8a1ZmQ5rMAiQw',
    appId: '1:2852225446:ios:b612a3b9ead4c7a1074f67',
    messagingSenderId: '2852225446',
    projectId: 'study-timer-backend',
    storageBucket: 'study-timer-backend.firebasestorage.app',
    iosClientId: '2852225446-sr637n90daipvu90uhl5d55d9gaj25km.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyTimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGCer_T_1S60YWAfbUhv8a1ZmQ5rMAiQw',
    appId: '1:2852225446:ios:b612a3b9ead4c7a1074f67',
    messagingSenderId: '2852225446',
    projectId: 'study-timer-backend',
    storageBucket: 'study-timer-backend.firebasestorage.app',
    iosClientId: '2852225446-sr637n90daipvu90uhl5d55d9gaj25km.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyTimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMCHAaZjmXBQABr5NP3SGTmQPWEBMPVG4',
    appId: '1:2852225446:web:14a17c568fe32943074f67',
    messagingSenderId: '2852225446',
    projectId: 'study-timer-backend',
    authDomain: 'study-timer-backend.firebaseapp.com',
    storageBucket: 'study-timer-backend.firebasestorage.app',
    measurementId: 'G-K7MTDG79X8',
  );
}
